In [1]:
import numpy as np
import pandas
from gurobipy import *

## Exemple jouet30

In [6]:
P = np.array(( ((0,0.875,0.0625,0.0625),(0,0.75,0,0.25 ),(0,0,0.5,0.5),(0,0,0,1)) , ((0.875,0,0.125,0),(0,0.75,0.125,0.125 ),(0.8,0,0.2,0),(0,0,0,1))  , ((0,0,1,0),(1,0,0,0 ),(0,1,0,0),(0,0,0,1))  ))
R = np.array(((0, 4000, 6000), (1000,4000 ,6000),(3000,4000,6000),(3000,4000,6000)))
gamma = 0.9999
print("matrices de transitions:")
print(P)
print("matrices de rewards:")
print(R)

matrices de transitions:
[[[0.     0.875  0.0625 0.0625]
  [0.     0.75   0.     0.25  ]
  [0.     0.     0.5    0.5   ]
  [0.     0.     0.     1.    ]]

 [[0.875  0.     0.125  0.    ]
  [0.     0.75   0.125  0.125 ]
  [0.8    0.     0.2    0.    ]
  [0.     0.     0.     1.    ]]

 [[0.     0.     1.     0.    ]
  [1.     0.     0.     0.    ]
  [0.     1.     0.     0.    ]
  [0.     0.     0.     1.    ]]]
matrices de rewards:
[[   0 4000 6000]
 [1000 4000 6000]
 [3000 4000 6000]
 [3000 4000 6000]]


In [7]:
P[1][1,1]

0.75

In [9]:
nbS = 4
nbA = 3
m = Model("MDPjouet30")     

# declaration variables de decision
v = []
for i in range(nbS):
    v.append(m.addVar(vtype=GRB.CONTINUOUS)) 

        
# maj du modele pour integrer les nouvelles variables
m.update()

obj = LinExpr();

for i in range(nbS):
    obj += v[i]/nbS   
# definition de l'objectif
m.setObjective(obj,GRB.MAXIMIZE)

# Definition des contraintes
for i in range(nbS):
    for j in range(nbA):
        sums = 0
        for k in range(nbS):
            sums = sums + gamma*P[j][i,k]*v[k]
        m.addConstr( v[i] <= R[i,j] + sums, "Contrainte%d" % i) #r(s,a)+ \sum_{s'} p(s'|s,a) h(s')

# Resolution
m.optimize()

print("")                
print('Solution optimale:')
for i in range(nbS):
        print('v%d'%(i+1), '=', v[i])
#print('Valeur de la fonction objectif (somme des V(S)) :', m.objVal)

Gurobi Optimizer version 9.1.1 build v9.1.1rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 12 rows, 4 columns and 24 nonzeros
Model fingerprint: 0x48b043eb
Coefficient statistics:
  Matrix range     [1e-04, 1e+00]
  Objective range  [3e-01, 3e-01]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+03, 6e+03]
Presolve removed 5 rows and 1 columns
Presolve time: 0.01s
Presolved: 7 rows, 3 columns, 15 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    5.0000000e+29   1.500350e+30   5.000000e-01      0s
       2    2.9993023e+07   0.000000e+00   0.000000e+00      0s

Solved in 2 iterations and 0.01 seconds
Optimal objective  2.999302332e+07

Solution optimale:
v1 = <gurobi.Var C0 (value 29989419.800716452)>
v2 = <gurobi.Var C1 (value 29992002.39928351)>
v3 = <gurobi.Var C2 (value 29990671.091959085)>
v4 = <gurobi.Var C3 (value 30000000.000003304)>
